version: '3'

services:
  airafraik:
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
      PGUSER: ${USER}
      PGCONNECT_TMIEOUT: 300
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
